[project]
name = "rnrgeek_scraper"
version = "0.1.0"
description = "Download Rock and Roll Geek Show episodes from Podbean.com"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4",
    "lxml",
    "requests",
]
